name: xinglianjiqian

on:
  workflow_dispatch:
  schedule:
    - cron: '39 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xinglianjiqian
        env:
          u0802: ${{ secrets.u0802 }}
        run: |
          echo $u0802 | jq -r .s9 | /bin/bash
          echo $mthod4916 | jq -r .caol68 | /bin/bash
          echo $xspf5371 | jq -r .bq829 | /bin/bash
          echo $gfr651 | jq -r .ptb978 | /bin/bash
          echo $frgd95647 | jq -r .jrpyr608 | /bin/bash
          echo $vij30 | jq -r .y9 | /bin/bash
          echo $sre929 | jq -r .vgwwi13229 | /bin/bash
          echo $et8 | jq -r .ha30748 | /bin/bash
          echo $i28 | jq -r .xlkcl716 | /bin/bash
          echo $i90 | jq -r .os55524 | /bin/bash
          echo $ry96365 | jq -r .h806 | /bin/bash
          echo $q767 | jq -r .wmo9254 | /bin/bash

