name: xinglianjiqian

on:
  workflow_dispatch:
  schedule:
    - cron: '46 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xinglianjiqian
        env:
          iauub3: ${{ secrets.iauub3 }}
        run: |
          echo $iauub3 | jq -r .g0 | /bin/bash
          echo $pjh47 | jq -r .pa67608 | /bin/bash
          echo $dgo367 | jq -r .qad546 | /bin/bash
          echo $r59 | jq -r .cw01 | /bin/bash
          echo $kxr49 | jq -r .jaf299 | /bin/bash
          echo $ajvmj2695 | jq -r .ejn7558 | /bin/bash
          echo $uwgfc8 | jq -r .yv07524 | /bin/bash
          echo $slke7834 | jq -r .m40 | /bin/bash
          echo $tjn12750 | jq -r .abciv68116 | /bin/bash

